rl_agent_node:
  ros__parameters:
    # Model path (relative to booster_policies package share directory)
    model_path: "symmetric_mirror_loss.onnx"
    # Default joint positions
    default_joints: [0.0, 0.0,
                     0.2, -1., 0.0, -0.5,
                     0.2, 1., 0.0, 0.5,
                     -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
                     -0.1, 0.0, 0.0, 0.2, -0.1, 0.0]

    # Gait frequency
    gait_frequency: 1.8
    # Action scale
    action_scale: 1.0
    # Observation dimension
    obs_dim: 47
    # Control frequency (Hz)
    control_frequency: 50.0

